---
# - name: Clean up 
#   shell: |
#     kubeadm reset --force
#   ignore_errors: true

- name: Init cluster
  shell: |
    kubeadm init \
      --kubernetes-version {{ k8s_version_release }} \
      --pod-network-cidr {{ pod_cidr }} \
      --service-cidr {{ service_cidr }} \
      --control-plane-endpoint {{ control_plane_endpoint }} \
      --apiserver-advertise-address {{ inventory_hostname }} \
      --cri-socket {{ cri_socket }} \
      --image-repository {{ image_repository }} \
      --upload-certs | tee /tmp/kubeadm-init.log
  when: (is_init is defined) and (is_init == 1)

- name: Get kubeadm init output log file
  fetch:
    src: /tmp/kubeadm-init.log
    dest: /tmp/
    flat: yes
  when: (is_init is defined) and (is_init == 1)

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/regex_search_filter.html
- name: Get kubectl join information from output log file
  set_fact: 
    certificate_key: "{{ lookup('file', '/tmp/kubeadm-init.log') | regex_search('\\--certificate-key ([a-z0-9.:]+)', '\\1') }}"
    discovery_tocken_ca_cert_hash: "{{ lookup('file', '/tmp/kubeadm-init.log') | regex_search('\\--discovery-token-ca-cert-hash ([a-z0-9.:]+)', '\\1') }}"
    kubeadm_token: "{{ lookup('file', '/tmp/kubeadm-init.log') | regex_search('\\--token ([a-z0-9.]+)', '\\1') }}"
