---
# Install cni - calico
- name: Copy file - calico custom resource
  template:
    src: calico-custom-resource.j2
    dest: /root/calico-custom-resource.yaml
  when: (is_init is defined) and (is_init == 1)

- name: Copy file - calico tiger operator
  template:
    src: tigera-operator.j2
    dest: /root/tigera-operator.yaml
  when: (is_init is defined) and (is_init == 1)

- name: Install Calico CNI
  # shell: |
  #   kubectl taint nodes --all node-role.kubernetes.io/control-plane- && \
  #   kubectl create -f /root/tigera-operator.yaml && \
  #   kubectl create -f /root/calico-custom-resource.yaml
  shell: |
    kubectl create -f /root/tigera-operator.yaml && \
    kubectl create -f /root/calico-custom-resource.yaml
  when: (is_init is defined) and (is_init == 1)

- name: Delete 10-containerd-net.conflist
  file:
    path: /etc/cni/net.d/10-containerd-net.conflist
    state: absent